apiVersion: v1
kind: Secret
metadata:
  name: newrelic-bundle-secret
  namespace: newrelic
type: Opaque
stringData:
  # New Relic UI → (account) → API Keys → License key
  licenseKey: "<NEW_RELIC_LICENSE_KEY>"
