apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-deployment
  namespace: gearflow
  labels:
    app: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:latest
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: ui
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
